feat: massive lint and regenerate apps

diff --git a/bin/cat_color b/bin/cat_color
--- a/bin/cat_color
+++ b/bin/cat_color
@@ -15,18 +15,18 @@
 
 function cat_color ()
 {
-    builtin local bat_bin;
-    builtin local bat_filename;
-    builtin local cat_bin;
-    builtin local _arg;
+    \builtin local bat_bin;
+    \builtin local bat_filename;
+    \builtin local cat_bin;
+    \builtin local _arg;
     cat_bin="$(require 'cat')";
     if [[ -z ${cat_bin} ]]; then
-        builtin exit 1;
+        \builtin exit 1;
     fi;
     bat_bin="$(which_bin 'bat')";
     if [[ -z ${bat_bin} ]]; then
         "${cat_bin}" "${@}";
-        builtin return 0;
+        \builtin return 0;
     fi;
     bat_filename='';
     for _arg in "${@}";
@@ -37,10 +37,10 @@ function cat_color ()
     done;
     if [[ -d ${1:-} ]]; then
         "${cat_bin}" "${@}";
-        builtin return 0;
+        \builtin return 0;
     fi;
     "${cat_bin}" "${@}" | bat_fun --style=plain --paging=never --theme 'gruvbox-dark' "${bat_filename[@]}" --color auto;
-    builtin return 0
+    \builtin return 0
 }
 
 function bat_fun ()
@@ -53,7 +53,9 @@ function bat_fun ()
         bat_bin="$(which_bin 'batcat')";
     fi;
     if [[ -n ${bat_bin} ]]; then
-        bat_avail="$("${bat_bin}" -V 2> /dev/null > /dev/null || \builtin echo -ne "${?}")";
+        bat_avail="$(
+      "${bat_bin}" -V 2> /dev/null > /dev/null || \builtin echo -ne "${?}"
+    )";
     fi;
     cat_bin="$(which_bin 'cat')";
     if [[ -n ${bat_bin} && -z ${bat_avail} ]]; then
@@ -66,13 +68,13 @@ function bat_fun ()
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -82,14 +84,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/conda_priv_fun b/bin/conda_priv_fun
--- a/bin/conda_priv_fun
+++ b/bin/conda_priv_fun
@@ -15,9 +15,9 @@
 
 function conda_priv_fun ()
 {
-    local conda_bin;
-    local env_name;
-    local conda_env_exports;
+    \builtin local conda_bin;
+    \builtin local env_name;
+    \builtin local conda_env_exports;
     conda_bin="$(get_conda_bin)";
     if [[ -z ${1:-} ]]; then
         "${conda_bin}" --help;
@@ -30,9 +30,9 @@ function conda_priv_fun ()
         else
             conda_env_exports="$("${conda_bin}" shell.posix activate "${env_name}")";
         fi;
-        builtin eval "${conda_env_exports}";
-        builtin hash -r;
-        builtin return 0;
+        \builtin eval "${conda_env_exports}";
+        \builtin hash -r;
+        \builtin return 0;
     fi;
     "${conda_bin}" "${@:-}";
     \builtin return 0
@@ -40,48 +40,50 @@ function conda_priv_fun ()
 
 function dirname_pure ()
 {
-    local tmp=${1:-.};
-    [[ $tmp != *[!/]* ]] && {
-        builtin printf '/\n';
-        builtin return
+    \builtin local tmp_var;
+    tmp_var="${1:-.}";
+    [[ $tmp_var != *[!/]* ]] && {
+        \builtin printf '/\n';
+        \builtin return
     };
-    tmp=${tmp%%"${tmp##*[!/]}"};
-    [[ $tmp != */* ]] && {
-        builtin printf '.\n';
-        builtin return
+    tmp_var=${tmp_var%%"${tmp_var##*[!/]}"};
+    [[ $tmp_var != */* ]] && {
+        \builtin printf '.\n';
+        \builtin return
     };
-    tmp=${tmp%/*};
-    tmp=${tmp%%"${tmp##*[!/]}"};
-    printf '%s\n' "${tmp:-/}"
+    tmp_var=${tmp_var%/*};
+    tmp_var=${tmp_var%%"${tmp_var##*[!/]}"};
+    \builtin printf '%s\n' "${tmp_var:-/}";
+    \builtin return 0
 }
 
 function download ()
 {
     function download_usage ()
     {
-        builtin echo -ne "usage: download <URL> [<OUTPUT_DIR>] [<THREADS>]\n" 1>&2
+        \builtin echo -ne "usage: download <URL> [<OUTPUT_DIR>] [<THREADS>]\n" 1>&2
     };
     if [[ ${#} -eq 0 ]]; then
         download_usage;
-        unset download_usage;
-        exit 1;
+        \builtin unset download_usage;
+        \builtin exit 1;
     fi;
     if [[ ${1:-} == '-h' ]]; then
         download_usage;
-        unset download_usage;
-        return 0;
+        \builtin unset download_usage;
+        \builtin return 0;
     fi;
-    unset download_usage;
-    local get_url;
-    local dir_output;
-    local thread_num;
-    local output_filename;
-    local output_basename;
-    local realpath_bin;
-    local wget_bin;
-    local curl_bin;
-    local aria_bin;
-    local cache_path;
+    \builtin unset download_usage;
+    \builtin local get_url;
+    \builtin local dir_output;
+    \builtin local thread_num;
+    \builtin local output_filename;
+    \builtin local output_basename;
+    \builtin local realpath_bin;
+    \builtin local wget_bin;
+    \builtin local curl_bin;
+    \builtin local aria_bin;
+    \builtin local cache_path;
     get_url="${1:-}";
     dir_output="${2:-}";
     realpath_bin="$(require 'realpath')";
@@ -109,22 +111,22 @@ function download ()
                 "${aria_bin}" --continue=true -s "${thread_num}" -x "${thread_num}" -j 1 -k 1M -d "${dir_output}" --out="${output_basename}" --quiet=true --check-integrity=true --check-certificate=false "${get_url}";
             else
                 exit_fun 'No download method available';
-                exit 1;
+                \builtin exit 1;
             fi;
         fi;
     fi;
-    return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function get_conda_bin ()
 {
-    builtin local conda_bin;
+    \builtin local conda_bin;
     conda_bin="$(which_bin 'micromamba')";
     if [[ -z ${conda_bin} ]]; then
         conda_bin="$(which_bin 'mamba')";
@@ -138,10 +140,10 @@ function get_conda_bin ()
     fi;
     if [[ -z ${conda_bin} ]]; then
         exit_fun '`conda`, `mamba`, and `micromamba` are not available for this system';
-        builtin exit 1;
+        \builtin exit 1;
     fi;
-    builtin echo -ne "${conda_bin}";
-    builtin return 0
+    \builtin echo -ne "${conda_bin}";
+    \builtin return 0
 }
 
 function get_conda_platform ()
@@ -194,13 +196,13 @@ function get_conda_platform ()
 
 function get_nthreads ()
 {
-    local nproc_bin;
-    local lscpu_bin;
-    local grep_bin;
-    local num_threads;
-    local half_threads;
-    local max_threads_to_use;
-    local threads_to_use;
+    \builtin local nproc_bin;
+    \builtin local lscpu_bin;
+    \builtin local grep_bin;
+    \builtin local num_threads;
+    \builtin local half_threads;
+    \builtin local max_threads_to_use;
+    \builtin local threads_to_use;
     max_threads_to_use="${1:-8}";
     nproc_bin="$(which_bin 'nproc')";
     lscpu_bin="$(which_bin 'lscpu')";
@@ -219,8 +221,8 @@ function get_nthreads ()
                 if [[ -n ${sysctl_bin} && $(get_os_type) == darwin ]]; then
                     num_threads="$("${sysctl_bin}" -n hw.ncpu)";
                 else
-                    builtin echo -ne "4";
-                    return 0;
+                    \builtin echo -ne "4";
+                    \builtin return 0;
                 fi;
             fi;
         fi;
@@ -230,14 +232,14 @@ function get_nthreads ()
     if [[ ${threads_to_use} -gt ${max_threads_to_use} ]]; then
         threads_to_use="${max_threads_to_use}";
     fi;
-    builtin echo -ne "${threads_to_use}";
-    return 0
+    \builtin echo -ne "${threads_to_use}";
+    \builtin return 0
 }
 
 function get_os_arch ()
 {
-    local os_arch_str;
-    local uname_bin;
+    \builtin local os_arch_str;
+    \builtin local uname_bin;
     os_arch_str="${HOSTTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_arch_str} ]]; then
@@ -245,16 +247,17 @@ function get_os_arch ()
             os_arch_str="$("${uname_bin}" -m)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
-    builtin echo -ne "${os_arch_str}";
-    return 0
+    \builtin echo -ne "${os_arch_str}";
+    \builtin return 0
 }
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -262,34 +265,36 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function install_micromamba ()
 {
-    builtin local _usage="Usage: ${0} [--force] [--system]";
-    builtin unset _usage;
-    builtin local micromamba_bin;
-    builtin local conda_platform;
-    builtin local download_url;
-    builtin local _arg;
-    builtin local install_type;
-    builtin local force_flag;
-    builtin local inst_path;
-    builtin local link_path;
-    builtin local link_dir;
-    builtin local dl_path;
-    builtin local chmod_bin;
-    builtin local ln_bin;
-    builtin local rm_bin;
-    builtin local mkdir_bin;
+    \builtin local _usage;
+    _usage="${0} [--force] [--system]";
+    \builtin unset _usage;
+    \builtin local micromamba_bin;
+    \builtin local conda_platform;
+    \builtin local download_url;
+    \builtin local _arg;
+    \builtin local install_type;
+    \builtin local force_flag;
+    \builtin local inst_path;
+    \builtin local link_path;
+    \builtin local link_dir;
+    \builtin local dl_path;
+    \builtin local chmod_bin;
+    \builtin local ln_bin;
+    \builtin local rm_bin;
+    \builtin local mkdir_bin;
     force_flag='0';
-    for _arg in "${@}";
+    for _arg in "${@:-}";
     do
         if [[ ${_arg} == --force ]]; then
             force_flag='1';
@@ -343,7 +348,7 @@ function install_micromamba ()
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -353,14 +358,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/create_log b/bin/create_log
--- a/bin/create_log
+++ b/bin/create_log
@@ -15,16 +15,16 @@
 
 function create_log ()
 {
-    local _usage;
+    \builtin local _usage;
     _usage="Usage: ${0} <APP_NAME> [<DIR>]/logs";
-    unset _usage;
-    local base_path;
-    local app_name;
-    local log_path;
-    local time_str;
-    local mkdir_bin;
-    local touch_bin;
-    local rand_str;
+    \builtin unset _usage;
+    \builtin local base_path;
+    \builtin local app_name;
+    \builtin local log_path;
+    \builtin local time_str;
+    \builtin local mkdir_bin;
+    \builtin local touch_bin;
+    \builtin local rand_str;
     app_name="${1:-}";
     base_path="${2:-}";
     if [[ -z ${base_path} ]]; then
@@ -51,13 +51,13 @@ function create_log ()
 
 function __get_hash ()
 {
-    local hash_len;
-    local hash_str;
-    local ssl_bin;
+    \builtin local hash_len;
+    \builtin local hash_str;
+    \builtin local ssl_bin;
     hash_len="${1:-6}";
     if [[ ${hash_len} -eq 0 ]]; then
         exit_fun "Hash length can not be set to '0'";
-        exit 1;
+        \builtin exit 1;
     fi;
     ssl_bin="$(require 'openssl')";
     if [ -n "${ssl_bin}" ]; then
@@ -71,10 +71,10 @@ function __get_hash ()
 
 function __get_hash_fallback ()
 {
-    local hash_len;
-    local i;
-    local rand_num;
-    local hash_str;
+    \builtin local hash_len;
+    \builtin local i;
+    \builtin local rand_num;
+    \builtin local hash_str;
     hash_len="${1:-6}";
     hash_str='';
     for ((i = 0 ; i < hash_len ; i++))
@@ -137,23 +137,23 @@ function __get_hash_fallback ()
 
 function __get_tz_timestamp ()
 {
-    local timestamp;
-    local date_bin;
+    \builtin local timestamp;
+    \builtin local date_bin;
     date_bin="$(require 'date')";
     timestamp="$(TZ='US/Eastern' "${date_bin}" '+%Y%m%d-%H%M%S')";
-    builtin echo -ne "${timestamp}";
-    return 0
+    \builtin echo -ne "${timestamp}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -163,14 +163,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -17,29 +17,29 @@ function download ()
 {
     function download_usage ()
     {
-        builtin echo -ne "usage: download <URL> [<OUTPUT_DIR>] [<THREADS>]\n" 1>&2
+        \builtin echo -ne "usage: download <URL> [<OUTPUT_DIR>] [<THREADS>]\n" 1>&2
     };
     if [[ ${#} -eq 0 ]]; then
         download_usage;
-        unset download_usage;
-        exit 1;
+        \builtin unset download_usage;
+        \builtin exit 1;
     fi;
     if [[ ${1:-} == '-h' ]]; then
         download_usage;
-        unset download_usage;
-        return 0;
+        \builtin unset download_usage;
+        \builtin return 0;
     fi;
-    unset download_usage;
-    local get_url;
-    local dir_output;
-    local thread_num;
-    local output_filename;
-    local output_basename;
-    local realpath_bin;
-    local wget_bin;
-    local curl_bin;
-    local aria_bin;
-    local cache_path;
+    \builtin unset download_usage;
+    \builtin local get_url;
+    \builtin local dir_output;
+    \builtin local thread_num;
+    \builtin local output_filename;
+    \builtin local output_basename;
+    \builtin local realpath_bin;
+    \builtin local wget_bin;
+    \builtin local curl_bin;
+    \builtin local aria_bin;
+    \builtin local cache_path;
     get_url="${1:-}";
     dir_output="${2:-}";
     realpath_bin="$(require 'realpath')";
@@ -67,28 +67,28 @@ function download ()
                 "${aria_bin}" --continue=true -s "${thread_num}" -x "${thread_num}" -j 1 -k 1M -d "${dir_output}" --out="${output_basename}" --quiet=true --check-integrity=true --check-certificate=false "${get_url}";
             else
                 exit_fun 'No download method available';
-                exit 1;
+                \builtin exit 1;
             fi;
         fi;
     fi;
-    return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function get_nthreads ()
 {
-    local nproc_bin;
-    local lscpu_bin;
-    local grep_bin;
-    local num_threads;
-    local half_threads;
-    local max_threads_to_use;
-    local threads_to_use;
+    \builtin local nproc_bin;
+    \builtin local lscpu_bin;
+    \builtin local grep_bin;
+    \builtin local num_threads;
+    \builtin local half_threads;
+    \builtin local max_threads_to_use;
+    \builtin local threads_to_use;
     max_threads_to_use="${1:-8}";
     nproc_bin="$(which_bin 'nproc')";
     lscpu_bin="$(which_bin 'lscpu')";
@@ -107,8 +107,8 @@ function get_nthreads ()
                 if [[ -n ${sysctl_bin} && $(get_os_type) == darwin ]]; then
                     num_threads="$("${sysctl_bin}" -n hw.ncpu)";
                 else
-                    builtin echo -ne "4";
-                    return 0;
+                    \builtin echo -ne "4";
+                    \builtin return 0;
                 fi;
             fi;
         fi;
@@ -118,14 +118,14 @@ function get_nthreads ()
     if [[ ${threads_to_use} -gt ${max_threads_to_use} ]]; then
         threads_to_use="${max_threads_to_use}";
     fi;
-    builtin echo -ne "${threads_to_use}";
-    return 0
+    \builtin echo -ne "${threads_to_use}";
+    \builtin return 0
 }
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -133,17 +133,18 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -153,14 +154,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/exec_remote b/bin/exec_remote
--- a/bin/exec_remote
+++ b/bin/exec_remote
@@ -15,29 +15,36 @@
 
 function exec_remote ()
 {
-    local _usage="${0} <HOST> '<COMMAND>'";
-    unset _usage;
-    local _debug_var="${DEBUG:-false}";
-    [[ "${_debug_var}" == true ]] && set -o xtrace;
-    local host_target;
-    local ssh_bin;
-    local var_res;
-    host_target="${1}";
+    \builtin local _usage="${0} <HOST> '<COMMAND>'";
+    \builtin unset _usage;
+    \builtin local _debug_var;
+    _debug_var="${DEBUG:-false}";
+    if [[ "${_debug_var}" == true ]]; then
+        \builtin set -o xtrace;
+    fi;
+    \builtin local host_target;
+    \builtin local ssh_bin;
+    \builtin local var_res;
+    host_target="${1:-}";
+    if [[ -z "${host_target}" ]]; then
+        exit_fun "Invalid execution.\nUsage: ${_usage}\n";
+        \builtin exit 1;
+    fi;
     ssh_bin="$(require 'ssh')";
     var_res="$("${ssh_bin}" -t "${host_target}" "${@:2}")";
-    builtin echo "${var_res}";
-    return 0
+    \builtin echo "${var_res}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -47,14 +54,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/get_hostname b/bin/get_hostname
--- a/bin/get_hostname
+++ b/bin/get_hostname
@@ -15,9 +15,9 @@
 
 function get_hostname ()
 {
-    local hostname_str;
-    local hostname_bin;
-    local uname_bin;
+    \builtin local hostname_str;
+    \builtin local hostname_bin;
+    \builtin local uname_bin;
     hostname_str="${HOSTNAME}";
     hostname_bin="$(which_bin 'hostname')";
     uname_bin="$(which_bin 'uname')";
@@ -29,16 +29,17 @@ function get_hostname ()
                 hostname_str="$("${uname_bin}" -n)";
             else
                 exit_fun "'hostname' command not available";
+                \builtin exit 1;
             fi;
         fi;
     fi;
-    builtin echo -ne "${hostname_str}";
-    return 0
+    \builtin echo -ne "${hostname_str}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
diff --git a/bin/get_nthreads b/bin/get_nthreads
--- a/bin/get_nthreads
+++ b/bin/get_nthreads
@@ -15,13 +15,13 @@
 
 function get_nthreads ()
 {
-    local nproc_bin;
-    local lscpu_bin;
-    local grep_bin;
-    local num_threads;
-    local half_threads;
-    local max_threads_to_use;
-    local threads_to_use;
+    \builtin local nproc_bin;
+    \builtin local lscpu_bin;
+    \builtin local grep_bin;
+    \builtin local num_threads;
+    \builtin local half_threads;
+    \builtin local max_threads_to_use;
+    \builtin local threads_to_use;
     max_threads_to_use="${1:-8}";
     nproc_bin="$(which_bin 'nproc')";
     lscpu_bin="$(which_bin 'lscpu')";
@@ -40,8 +40,8 @@ function get_nthreads ()
                 if [[ -n ${sysctl_bin} && $(get_os_type) == darwin ]]; then
                     num_threads="$("${sysctl_bin}" -n hw.ncpu)";
                 else
-                    builtin echo -ne "4";
-                    return 0;
+                    \builtin echo -ne "4";
+                    \builtin return 0;
                 fi;
             fi;
         fi;
@@ -51,20 +51,20 @@ function get_nthreads ()
     if [[ ${threads_to_use} -gt ${max_threads_to_use} ]]; then
         threads_to_use="${max_threads_to_use}";
     fi;
-    builtin echo -ne "${threads_to_use}";
-    return 0
+    \builtin echo -ne "${threads_to_use}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -72,17 +72,18 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -92,14 +93,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/get_os_arch b/bin/get_os_arch
--- a/bin/get_os_arch
+++ b/bin/get_os_arch
@@ -15,8 +15,8 @@
 
 function get_os_arch ()
 {
-    local os_arch_str;
-    local uname_bin;
+    \builtin local os_arch_str;
+    \builtin local uname_bin;
     os_arch_str="${HOSTTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_arch_str} ]]; then
@@ -24,15 +24,16 @@ function get_os_arch ()
             os_arch_str="$("${uname_bin}" -m)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
-    builtin echo -ne "${os_arch_str}";
-    return 0
+    \builtin echo -ne "${os_arch_str}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
diff --git a/bin/get_os_type b/bin/get_os_type
--- a/bin/get_os_type
+++ b/bin/get_os_type
@@ -15,8 +15,8 @@
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -24,17 +24,18 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
diff --git a/bin/radian_fun b/bin/radian_fun
--- a/bin/radian_fun
+++ b/bin/radian_fun
@@ -15,12 +15,24 @@
 
 function radian_fun ()
 {
-    local r_bin;
-    local py_bin;
+    \builtin local r_bin;
+    \builtin local py_bin;
     py_bin="$(which_bin 'python3')";
-    _IS_RADIAN=true "${py_bin}" -m radian;
-    --r-binary="${r_bin}" --profile="${HOME}/.config/radian/profile" --global-history --quiet "${@}";
-    return 0
+    if [[ -z "${py_bin}" ]]; then
+        py_bin="$(which_bin 'python')";
+    fi;
+    if [[ -z "${py_bin}" ]]; then
+        exit_fun "'python3' or 'python' is not available on '${PATH}'";
+        \builtin exit 1;
+    fi;
+    _IS_RADIAN=true "${py_bin}" -m radian --r-binary="${r_bin}" --profile="${HOME}/.config/radian/profile" --global-history --quiet "${@}";
+    \builtin return 0
+}
+
+function exit_fun ()
+{
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
+    \builtin exit 1
 }
 
 function which_bin ()
diff --git a/bin/rm_safe b/bin/rm_safe
--- a/bin/rm_safe
+++ b/bin/rm_safe
@@ -15,41 +15,44 @@
 
 function rm_safe ()
 {
-    builtin local rm_bin;
-    builtin local realpath_bin;
-    builtin local safe_dirs_arr;
-    builtin local _safe_dir;
-    builtin local safe_path;
-    builtin local _arg;
-    builtin local path_arg;
+    \builtin local rm_bin;
+    \builtin local realpath_bin;
+    \builtin local safe_dirs_arr;
+    \builtin local _safe_dir;
+    \builtin local safe_path;
+    \builtin local _arg;
+    \builtin local path_arg;
     rm_bin="$(which_bin 'rm')";
     if [[ -z ${rm_bin} ]]; then
         exit_fun "'rm' command not available on \${PATH}";
-        builtin exit 1;
+        \builtin exit 1;
     fi;
     realpath_bin="$(which_bin 'realpath')";
-    declare -a safe_dirs_arr=("${HOME}" "${HOME}/Documents" "${HOME}/documents" "${HOME}/projects" "${HOME}/workspaces" "/Users/${USER}" "/home/${USER}" '${HOME}' '/Users/${USER}' '/home/${USER}' '/root' '/home' '/data' '/System' '/User' '/Volumes' '/');
+    \builtin declare -a safe_dirs_arr;
+    safe_dirs_arr=("${HOME}" "${HOME}/Documents" "${HOME}/documents" "${HOME}/projects" "${HOME}/workspaces" "/Users/${USER}" "/home/${USER}" '${HOME}' '/Users/${USER}' '/home/${USER}' '/root' '/home' '/data' '/System' '/User' '/Volumes' '/');
     for _arg in "${@}";
     do
-        path_arg="$("${realpath_bin}" "${_arg}" 2> /dev/null || builtin echo -ne '')";
+        path_arg="$("${realpath_bin}" 2> /dev/null "${_arg}" || \builtin echo -ne '')";
         if [[ -n ${path_arg} ]]; then
             for _safe_dir in "${safe_dirs_arr[@]}";
             do
-                safe_path="$("${realpath_bin}" "${_safe_dir}" 2> /dev/null || builtin echo -ne '')";
+                safe_path="$(
+          "${realpath_bin}" 2> /dev/null "${_safe_dir}" || \builtin echo -ne ''
+        )";
                 if [[ ${safe_path} == "${path_arg}" ]]; then
-                    builtin echo -ne "Error: '${safe_path}' is a **protected** directory. Don't delete it!\n";
-                    builtin exit 1;
+                    \builtin echo -ne "Error: '${safe_path}' is a **protected** directory. Don't delete it!\n";
+                    \builtin exit 1;
                 fi;
             done;
         fi;
     done;
     "${rm_bin}" "${@}";
-    builtin return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
diff --git a/bin/sleep_pure b/bin/sleep_pure
--- a/bin/sleep_pure
+++ b/bin/sleep_pure
@@ -15,22 +15,23 @@
 
 function sleep_pure ()
 {
-    local sleep_time;
-    sleep_time="${1}";
+    \builtin local sleep_time;
+    sleep_time="${1:-}";
     if [[ -z ${sleep_time} ]]; then
         exit_fun 'invalid option';
+        \builtin exit 1;
     fi;
     if [[ ${OSTYPE} =~ darwin ]]; then
-        builtin command -p sleep "${sleep_time}";
+        \builtin command -p sleep "${sleep_time}";
     else
-        builtin read -rt "${sleep_time}" <> <(:) || :;
+        \builtin read -rt "${sleep_time}" 0<> <(:) || :;
     fi;
-    return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
diff --git a/bin/slurm_cancel_all_jobs b/bin/slurm_cancel_all_jobs
--- a/bin/slurm_cancel_all_jobs
+++ b/bin/slurm_cancel_all_jobs
@@ -13,11 +13,24 @@
 
 [[ "${BASH_VERSINFO[0]}" -lt 4 ]] && { \builtin echo >&2 "Error: Bash >=4 required"; \builtin exit 1; }
 
-function highlight_fun ()
+function slurm_cancel_all_jobs ()
 {
-    \builtin local rg_bin;
-    rg_bin="$(require 'rg')";
-    "${rg_bin}" --passthru "${@:-}";
+    \builtin local _usage="Usage: ${0} [USER_NAME]";
+    \builtin unset _usage;
+    \builtin local scancel_bin;
+    \builtin local user_name;
+    user_name="${1:-${USER:-}}";
+    if [[ -z "${user_name}" ]]; then
+        exit_fun 'Error: User name is required.';
+        \builtin exit 1;
+    fi;
+    scancel_bin="$(require 'scancel')";
+    \builtin read -rp "Are you sure you want to cancel all jobs for user ${user_name}? [y/N] " confirm_cancel;
+    if [[ "${confirm_cancel}" != "y" ]]; then
+        \builtin echo "Aborting cancelation of jobs for user ${user_name}.";
+        \builtin return 0;
+    fi;
+    "${scancel_bin}" -u "${user_name}";
     \builtin return 0
 }
 
@@ -78,7 +91,7 @@ function which_bin ()
 }
 
 function main () {
-    highlight_fun "${@:-}";
+    slurm_cancel_all_jobs "${@:-}";
     \builtin return;
 }
 
diff --git a/bin/source_remote b/bin/source_remote
--- a/bin/source_remote
+++ b/bin/source_remote
@@ -15,23 +15,33 @@
 
 function source_remote ()
 {
-    builtin local script_url="$1";
-    builtin local curl_bin;
-    builtin local wget_bin;
-    curl_bin=($(which -a 'curl' || builtin echo -ne ''));
-    curl_bin="${curl_bin[0]}";
-    wget_bin=($(which -a 'wget' || builtin echo -ne ''));
-    wget_bin="${wget_bin[0]}";
+    \builtin local script_url;
+    \builtin local curl_bin;
+    \builtin local wget_bin;
+    script_url="${1:-}";
+    curl_bin="$(\builtin command -v curl 2>/dev/null || \builtin echo -ne '')";
+    wget_bin="$(\builtin command -v wget 2>/dev/null || \builtin echo -ne '')";
     if [[ -n ${curl_bin} ]]; then
-        builtin source /dev/stdin <<< "$("${curl_bin}" -f -s -S -L "${script_url}")";
+        \builtin source /dev/stdin <<< "$("${curl_bin}" -f -s -S -L "${script_url}")";
     else
         if [[ -n ${wget_bin} ]]; then
-            builtin source /dev/stdin <<< "$("${wget_bin}" -q -L -nv -O - "${script_url}")";
+            \builtin source /dev/stdin <<< "$("${wget_bin}" -q -L -nv -O - "${script_url}")";
         else
-            builtin echo -ne "Download tool not available. Install 'curl' or 'wget' to continue.\n" 1>&2;
-            builtin exit 1;
+            exit_fun "Download tool not available. Install 'curl' or 'wget' to continue.";
+            \builtin exit 1;
         fi;
-    fi
+    fi;
+    if [[ ! "${?:-1}" -eq 0 ]]; then
+        exit_fun "Failed to source script from '${script_url}'";
+        \builtin exit 1;
+    fi;
+    \builtin return 0
+}
+
+function exit_fun ()
+{
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
+    \builtin exit 1
 }
 
 function main () {
diff --git a/bin/ssh_forget b/bin/ssh_forget
--- a/bin/ssh_forget
+++ b/bin/ssh_forget
@@ -15,14 +15,14 @@
 
 function ssh_forget ()
 {
-    local keygen_bin;
-    local rm_bin;
-    local _host_name;
+    \builtin local keygen_bin;
+    \builtin local rm_bin;
+    \builtin local _host_name;
     rm_bin="$(which_bin 'rm')";
     keygen_bin="$(require 'ssh-keygen')";
     if [[ -z ${keygen_bin} ]]; then
         exit_fun '`ssh-keygen` is not available on PATH';
-        exit 1;
+        \builtin exit 1;
     fi;
     for _host_name in "${@}";
     do
@@ -31,18 +31,18 @@ function ssh_forget ()
     if [[ -f "${HOME}/.ssh/known_hosts.old" ]]; then
         "${rm_bin}" -f "${HOME}/.ssh/known_hosts.old";
     fi;
-    builtin return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -52,14 +52,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/ssh_generate_key b/bin/ssh_generate_key
--- a/bin/ssh_generate_key
+++ b/bin/ssh_generate_key
@@ -15,43 +15,50 @@
 
 function ssh_generate_key ()
 {
-    local _usage="usage: ${0} <USER> <HOST> <ID_FILE>";
-    unset _usage;
-    local ssh_user;
-    local ssh_host;
-    local key_name;
-    local key_type;
-    local key_args;
-    local ssh_keygen_bin;
-    ssh_user="${1}";
-    ssh_host="${2}";
-    key_name="${3}";
+    \builtin local _usage;
+    _usage="usage: ${0} <USER> <HOST> <ID_FILE>";
+    \builtin unset _usage;
+    \builtin local ssh_user;
+    \builtin local ssh_host;
+    \builtin local key_name;
+    \builtin local key_type;
+    \builtin local key_args;
+    \builtin local ssh_keygen_bin;
+    ssh_user="${1:-}";
+    ssh_host="${2:-}";
+    key_name="${3:-}";
+    if [[ -z ${ssh_user} || -z ${ssh_host} || -z ${key_name} ]]; then
+        exit_fun 'Missing required arguments. See usage.';
+        \builtin exit 1;
+    fi;
     key_type="${4:-ed25519}";
     case "${key_type}" in
         ed25519)
-            declare -a key_args=(-t ed25519 -a 200)
+            \builtin declare -a key_args;
+            key_args=('-t' 'ed25519' '-a' '200')
         ;;
         rsa)
-            declare -a key_args=(-t)
+            \builtin declare -a key_args;
+            key_args=(-t)
         ;;
         *)
-            exit 1
+            \builtin exit 1
         ;;
     esac;
     ssh_keygen_bin="$(require 'ssh-keygen')";
     "${ssh_keygen_bin}" "${key_args[@]}" -C "${ssh_user}@${ssh_host}" -f "${HOME}/.ssh/keys/${key_name}";
-    return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -61,14 +68,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/ssh_key_create_and_push b/bin/ssh_key_create_and_push
--- a/bin/ssh_key_create_and_push
+++ b/bin/ssh_key_create_and_push
@@ -15,18 +15,23 @@
 
 function ssh_key_create_and_push ()
 {
-    local _usage="usage: ${0} <USER> <HOST> <ID_FILE> [<PORT>|22]";
-    unset _usage;
-    local ssh_user;
-    local remote_ip;
-    local key_name;
-    local remote_port;
-    local key_dir;
-    local mkdir_bin;
-    local chmod_bin;
-    ssh_user="${1}";
-    remote_ip="${2}";
-    key_name="${3}";
+    \builtin local _usage;
+    _usage="usage: ${0} <USER> <HOST> <ID_FILE> [<PORT>|22]";
+    \builtin unset _usage;
+    \builtin local ssh_user;
+    \builtin local remote_ip;
+    \builtin local key_name;
+    \builtin local remote_port;
+    \builtin local key_dir;
+    \builtin local mkdir_bin;
+    \builtin local chmod_bin;
+    ssh_user="${1:-}";
+    remote_ip="${2:-}";
+    key_name="${3:-}";
+    if [[ -z ${ssh_user} || -z ${remote_ip} || -z ${key_name} ]]; then
+        exit_fun 'Missing required arguments. See usage.';
+        \builtin exit 1;
+    fi;
     remote_port="${4:-22}";
     key_dir="${HOME}/.ssh/keys";
     mkdir_bin="$(require 'mkdir')";
@@ -38,19 +43,19 @@ function ssh_key_create_and_push ()
     ssh_generate_key "${ssh_user}" "${remote_ip}" "${key_name}";
     ssha_fun "${key_dir}/${key_name}";
     ssh_send_key "${ssh_user}" "${remote_ip}" "${key_name}" "${remote_port}";
-    return 0
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -58,17 +63,18 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -78,14 +84,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
@@ -96,71 +102,90 @@ function require ()
 
 function ssh_generate_key ()
 {
-    local _usage="usage: ${0} <USER> <HOST> <ID_FILE>";
-    unset _usage;
-    local ssh_user;
-    local ssh_host;
-    local key_name;
-    local key_type;
-    local key_args;
-    local ssh_keygen_bin;
-    ssh_user="${1}";
-    ssh_host="${2}";
-    key_name="${3}";
+    \builtin local _usage;
+    _usage="usage: ${0} <USER> <HOST> <ID_FILE>";
+    \builtin unset _usage;
+    \builtin local ssh_user;
+    \builtin local ssh_host;
+    \builtin local key_name;
+    \builtin local key_type;
+    \builtin local key_args;
+    \builtin local ssh_keygen_bin;
+    ssh_user="${1:-}";
+    ssh_host="${2:-}";
+    key_name="${3:-}";
+    if [[ -z ${ssh_user} || -z ${ssh_host} || -z ${key_name} ]]; then
+        exit_fun 'Missing required arguments. See usage.';
+        \builtin exit 1;
+    fi;
     key_type="${4:-ed25519}";
     case "${key_type}" in
         ed25519)
-            declare -a key_args=(-t ed25519 -a 200)
+            \builtin declare -a key_args;
+            key_args=('-t' 'ed25519' '-a' '200')
         ;;
         rsa)
-            declare -a key_args=(-t)
+            \builtin declare -a key_args;
+            key_args=(-t)
         ;;
         *)
-            exit 1
+            \builtin exit 1
         ;;
     esac;
     ssh_keygen_bin="$(require 'ssh-keygen')";
     "${ssh_keygen_bin}" "${key_args[@]}" -C "${ssh_user}@${ssh_host}" -f "${HOME}/.ssh/keys/${key_name}";
-    return 0
+    \builtin return 0
 }
 
 function ssh_send_key ()
 {
-    local _usage="usage: ${0} <USER> <HOST> <ID_FILE> <HOST_PORT>";
-    unset _usage;
-    local ssh_user;
-    local ssh_host;
-    local key_name;
-    local ssh_port;
-    local ssh_cp_id_bin;
+    \builtin local _usage;
+    _usage="usage: ${0} <USER> <HOST> <ID_FILE> <HOST_PORT>";
+    \builtin unset _usage;
+    \builtin local ssh_user;
+    \builtin local ssh_host;
+    \builtin local key_name;
+    \builtin local ssh_port;
+    \builtin local ssh_cp_id_bin;
     ssh_cp_id_bin="$(require 'ssh-copy-id')";
-    ssh_user="${1}";
-    ssh_host="${2}";
-    key_name="${3}";
+    ssh_user="${1:-}";
+    ssh_host="${2:-}";
+    key_name="${3:-}";
+    if [[ -z ${ssh_user} || -z ${ssh_host} || -z ${key_name} ]]; then
+        exit_fun 'Missing required arguments. See usage.';
+        \builtin exit 1;
+    fi;
     ssh_port="${4:-22}";
     "${ssh_cp_id_bin}" -p "${ssh_port}" -i "${HOME}/.ssh/keys/${key_name}" "${ssh_user}@${ssh_host}";
-    return 0
+    \builtin return 0
 }
 
 function ssha_fun ()
 {
-    local _usage="usage: ${0} <KEY_FILE_PATH>";
-    unset _usage;
-    local ssh_agent_bin;
-    local ssh_add_bin;
-    local ssha_args;
-    local key_path;
-    local os_type;
-    key_path="${1}";
+    \builtin local _usage;
+    _usage="usage: ${0} <KEY_FILE_PATH>";
+    \builtin unset _usage;
+    \builtin local ssh_agent_bin;
+    \builtin local ssh_add_bin;
+    \builtin local ssha_args;
+    \builtin local key_path;
+    \builtin local os_type;
+    key_path="${1:-}";
+    if [[ -z ${key_path} ]]; then
+        exit_fun 'Missing required argument. See usage.';
+        \builtin exit 1;
+    fi;
     ssh_agent_bin="$(require 'ssh-agent')";
     ssh_add_bin="$(require 'ssh-add')";
-    declare -a ssha_args=();
+    \builtin declare -a ssha_args;
+    ssha_args=();
     os_type="$(get_os_type)";
     if [[ ${os_type} == darwin ]]; then
-        declare -a ssha_args=(--apple-use-keychain);
+        \builtin declare -a ssha_args;
+        ssha_args=('--apple-use-keychain');
     fi;
-    builtin eval "$("${ssh_agent_bin}")" && "${ssh_add_bin}" "${ssha_args[@]}" "${key_path}";
-    return 0
+    \builtin eval "$("${ssh_agent_bin}")" && "${ssh_add_bin}" "${ssha_args[@]}" "${key_path}";
+    \builtin return 0
 }
 
 function which_bin ()
diff --git a/bin/ssha_fun b/bin/ssha_fun
--- a/bin/ssha_fun
+++ b/bin/ssha_fun
@@ -15,35 +15,42 @@
 
 function ssha_fun ()
 {
-    local _usage="usage: ${0} <KEY_FILE_PATH>";
-    unset _usage;
-    local ssh_agent_bin;
-    local ssh_add_bin;
-    local ssha_args;
-    local key_path;
-    local os_type;
-    key_path="${1}";
+    \builtin local _usage;
+    _usage="usage: ${0} <KEY_FILE_PATH>";
+    \builtin unset _usage;
+    \builtin local ssh_agent_bin;
+    \builtin local ssh_add_bin;
+    \builtin local ssha_args;
+    \builtin local key_path;
+    \builtin local os_type;
+    key_path="${1:-}";
+    if [[ -z ${key_path} ]]; then
+        exit_fun 'Missing required argument. See usage.';
+        \builtin exit 1;
+    fi;
     ssh_agent_bin="$(require 'ssh-agent')";
     ssh_add_bin="$(require 'ssh-add')";
-    declare -a ssha_args=();
+    \builtin declare -a ssha_args;
+    ssha_args=();
     os_type="$(get_os_type)";
     if [[ ${os_type} == darwin ]]; then
-        declare -a ssha_args=(--apple-use-keychain);
+        \builtin declare -a ssha_args;
+        ssha_args=('--apple-use-keychain');
     fi;
-    builtin eval "$("${ssh_agent_bin}")" && "${ssh_add_bin}" "${ssha_args[@]}" "${key_path}";
-    return 0
+    \builtin eval "$("${ssh_agent_bin}")" && "${ssh_add_bin}" "${ssha_args[@]}" "${key_path}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
 function get_os_type ()
 {
-    local os_type_str;
-    local uname_bin;
+    \builtin local os_type_str;
+    \builtin local uname_bin;
     os_type_str="${OSTYPE}";
     uname_bin="$(which_bin 'uname')";
     if [[ -z ${os_type_str} ]]; then
@@ -51,17 +58,18 @@ function get_os_type ()
             os_type_str="$("${uname_bin}" -s)";
         else
             exit_fun "'uname' command not available";
+            \builtin exit 1;
         fi;
     fi;
     os_type_str="${os_type_str/[\-1-9]*/}";
     os_type_str="${os_type_str,,}";
-    builtin echo -ne "${os_type_str}";
-    return 0
+    \builtin echo -ne "${os_type_str}";
+    \builtin return 0
 }
 
 function require ()
 {
-    local cmd_str;
+    \builtin local cmd_str;
     \builtin local cmd_bin;
     \builtin local cmd_res;
     \builtin local full_cmd;
@@ -71,14 +79,14 @@ function require ()
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
         \builtin exit 1;
     fi;
-    if [[ ${#} -eq 1 ]]; then
+    if [[ ${#:-} -eq 1 ]]; then
         cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
         cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
-    if [[ -n ${cmd_res} ]]; then
+    if [[ -n "${cmd_res}" ]]; then
         \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
diff --git a/bin/sudo_check b/bin/sudo_check
--- a/bin/sudo_check
+++ b/bin/sudo_check
@@ -15,26 +15,27 @@
 
 function sudo_check ()
 {
-    local sudo_uid;
-    local sudo_bin;
-    local sudo_bool;
+    \builtin local sudo_uid;
+    \builtin local sudo_bin;
+    \builtin local sudo_bool;
     sudo_bin="$(which_bin 'sudo')";
     if [[ ${sudo_bin} == "" ]]; then
         exit_fun '`sudo` program not available';
+        \builtin exit 1;
     fi;
-    sudo_uid=$("${sudo_bin}" -n id -u 2> /dev/null || id -u);
+    sudo_uid=$("${sudo_bin}" -n id -u 2>/dev/null || id -u);
     if [[ "${sudo_uid}" == 0 ]]; then
         sudo_bool=true;
     else
         sudo_bool=false;
     fi;
-    builtin echo "${sudo_bool}";
-    return 0
+    \builtin echo "${sudo_bool}";
+    \builtin return 0
 }
 
 function exit_fun ()
 {
-    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?${1:-'An error occurred. Exiting.'}}";
     \builtin exit 1
 }
 
