chore: lint lib and rebuild apps

diff --git a/bin/require b/bin/require
--- a/bin/require
+++ b/bin/require
@@ -14,29 +14,29 @@
 require () 
 { 
     local cmd_str;
-    local cmd_bin;
-    local cmd_res;
-    local full_cmd;
+    \builtin local cmd_bin;
+    \builtin local cmd_res;
+    \builtin local full_cmd;
     cmd_str="${1:-}";
     cmd_bin="$(which_bin "${cmd_str}")";
     if [[ -z ${cmd_bin} ]]; then
         exit_fun "'${cmd_str}' executable not found in '\${PATH}'";
-        exit 1;
+        \builtin exit 1;
     fi;
     if [[ ${#} -eq 1 ]]; then
-        cmd_res="$("${cmd_bin}" --version 2>&1 || builtin echo -ne '')";
+        cmd_res="$("${cmd_bin}" --version 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} --version";
     else
-        cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || builtin echo -ne '')";
+        cmd_res="$("${cmd_bin}" "${@:2}" 2>&1 || \builtin echo -ne '')";
         full_cmd="${cmd_bin} ${*:2}";
     fi;
     if [[ -n ${cmd_res} ]]; then
-        builtin echo -ne "${cmd_bin}";
+        \builtin echo -ne "${cmd_bin}";
     else
         exit_fun "'${full_cmd}' can't be executed";
-        exit 1;
+        \builtin exit 1;
     fi;
-    exit 0
+    \builtin exit 0
 }
 which_bin () 
 { 
@@ -61,8 +61,8 @@ which_bin ()
 }
 exit_fun () 
 { 
-    : builtin local Error && Error=' ' && builtin unset -v Error && "${Error:?$1}";
-    builtin exit 1
+    : builtin local Error && Error=' ' && \builtin unset -v Error && "${Error:?$1}";
+    \builtin exit 1
 }
 
 function main () {
